//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IDashboardApiClient {

    /**
     * Get dashboard metrics
     * @return Successful Response
     */
    getMetrics(): Promise<DashboardMetricsSchema>;

    /**
     * Get full combined dashboard dataset
     * @return Successful Response
     */
    getFullData(): Promise<FullDashboardDataSchema>;

    /**
     * Get entity DAG dependency graph for Cytoscape
     * @return Successful Response
     */
    getDagGraph(): Promise<any>;

    /**
     * List all issues
     * @param status (optional) Filter by status (open, in-progress, blocked, done)
     * @param type (optional) Filter by type (feat, bug, debt, task, docs)
     * @param priority (optional) Filter by priority (critical, high, medium, low)
     * @param milestone (optional) Filter by milestone slug
     * @return Successful Response
     */
    listIssues(status?: Status | undefined, type?: Type | undefined, priority?: Priority | undefined, milestone?: Milestone | undefined): Promise<IssueSchema[]>;

    /**
     * Get issue details
     * @return Successful Response
     */
    getIssue(issue_id: string): Promise<IssueSchema>;

    /**
     * List all milestones
     * @return Successful Response
     */
    listMilestones(): Promise<MilestoneSchema[]>;

    /**
     * List all risks
     * @return Successful Response
     */
    listRisks(): Promise<RiskSchema[]>;

    /**
     * List all spikes
     * @return Successful Response
     */
    listSpikes(): Promise<SpikeSchema[]>;

    /**
     * List all session logs
     * @return Successful Response
     */
    listSessions(): Promise<SessionSchema[]>;

    /**
     * List all ADR decisions
     * @return Successful Response
     */
    listDecisions(): Promise<DecisionSchema[]>;

    /**
     * List all Knowledge Base articles
     * @param type (optional) Filter by category type
     * @param tag (optional) Filter by tag
     * @return Successful Response
     */
    listArticles(type?: Anonymous | undefined, tag?: Tag | undefined): Promise<KBArticleSchema[]>;

    /**
     * Search Knowledge Base and entities
     * @param q (optional) Search query string
     * @param tag (optional) Filter by tag
     * @param type (optional) Filter by entity type (kb, issue, decision, session)
     * @return Successful Response
     */
    searchKb(q?: string | undefined, tag?: Anonymous2 | undefined, type?: Anonymous3 | undefined): Promise<SearchResponse>;

    /**
     * Get Knowledge Base cross-link graph
     * @return Successful Response
     */
    getKbGraph(): Promise<KBGraphSchema>;

    /**
     * Get single Knowledge Base article
     * @return Successful Response
     */
    getArticle(slug: string): Promise<KBArticleSchema>;

    /**
     * Stream live repository changes via Server-Sent Events (SSE)
     * @return Successful Response
     */
    streamEvents(): Promise<any>;
}

export class DashboardApiClient implements IDashboardApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get dashboard metrics
     * @return Successful Response
     */
    getMetrics(): Promise<DashboardMetricsSchema> {
        let url_ = this.baseUrl + "/api/metrics";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetMetrics(_response);
        });
    }

    protected processGetMetrics(response: Response): Promise<DashboardMetricsSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DashboardMetricsSchema;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DashboardMetricsSchema>(null as any);
    }

    /**
     * Get full combined dashboard dataset
     * @return Successful Response
     */
    getFullData(): Promise<FullDashboardDataSchema> {
        let url_ = this.baseUrl + "/api/data";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetFullData(_response);
        });
    }

    protected processGetFullData(response: Response): Promise<FullDashboardDataSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as FullDashboardDataSchema;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FullDashboardDataSchema>(null as any);
    }

    /**
     * Get entity DAG dependency graph for Cytoscape
     * @return Successful Response
     */
    getDagGraph(): Promise<any> {
        let url_ = this.baseUrl + "/api/graph";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetDagGraph(_response);
        });
    }

    protected processGetDagGraph(response: Response): Promise<any> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<any>(null as any);
    }

    /**
     * List all issues
     * @param status (optional) Filter by status (open, in-progress, blocked, done)
     * @param type (optional) Filter by type (feat, bug, debt, task, docs)
     * @param priority (optional) Filter by priority (critical, high, medium, low)
     * @param milestone (optional) Filter by milestone slug
     * @return Successful Response
     */
    listIssues(status?: Status | undefined, type?: Type | undefined, priority?: Priority | undefined, milestone?: Milestone | undefined): Promise<IssueSchema[]> {
        let url_ = this.baseUrl + "/api/entities/issues?";
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (type === null)
            throw new globalThis.Error("The parameter 'type' cannot be null.");
        else if (type !== undefined)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        if (priority === null)
            throw new globalThis.Error("The parameter 'priority' cannot be null.");
        else if (priority !== undefined)
            url_ += "priority=" + encodeURIComponent("" + priority) + "&";
        if (milestone === null)
            throw new globalThis.Error("The parameter 'milestone' cannot be null.");
        else if (milestone !== undefined)
            url_ += "milestone=" + encodeURIComponent("" + milestone) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListIssues(_response);
        });
    }

    protected processListIssues(response: Response): Promise<IssueSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IssueSchema[];
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IssueSchema[]>(null as any);
    }

    /**
     * Get issue details
     * @return Successful Response
     */
    getIssue(issue_id: string): Promise<IssueSchema> {
        let url_ = this.baseUrl + "/api/entities/issues/{issue_id}";
        if (issue_id === undefined || issue_id === null)
            throw new globalThis.Error("The parameter 'issue_id' must be defined.");
        url_ = url_.replace("{issue_id}", encodeURIComponent("" + issue_id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetIssue(_response);
        });
    }

    protected processGetIssue(response: Response): Promise<IssueSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IssueSchema;
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IssueSchema>(null as any);
    }

    /**
     * List all milestones
     * @return Successful Response
     */
    listMilestones(): Promise<MilestoneSchema[]> {
        let url_ = this.baseUrl + "/api/entities/milestones";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListMilestones(_response);
        });
    }

    protected processListMilestones(response: Response): Promise<MilestoneSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MilestoneSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MilestoneSchema[]>(null as any);
    }

    /**
     * List all risks
     * @return Successful Response
     */
    listRisks(): Promise<RiskSchema[]> {
        let url_ = this.baseUrl + "/api/entities/risks";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListRisks(_response);
        });
    }

    protected processListRisks(response: Response): Promise<RiskSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RiskSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RiskSchema[]>(null as any);
    }

    /**
     * List all spikes
     * @return Successful Response
     */
    listSpikes(): Promise<SpikeSchema[]> {
        let url_ = this.baseUrl + "/api/entities/spikes";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListSpikes(_response);
        });
    }

    protected processListSpikes(response: Response): Promise<SpikeSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SpikeSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpikeSchema[]>(null as any);
    }

    /**
     * List all session logs
     * @return Successful Response
     */
    listSessions(): Promise<SessionSchema[]> {
        let url_ = this.baseUrl + "/api/entities/sessions";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListSessions(_response);
        });
    }

    protected processListSessions(response: Response): Promise<SessionSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SessionSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SessionSchema[]>(null as any);
    }

    /**
     * List all ADR decisions
     * @return Successful Response
     */
    listDecisions(): Promise<DecisionSchema[]> {
        let url_ = this.baseUrl + "/api/entities/decisions";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListDecisions(_response);
        });
    }

    protected processListDecisions(response: Response): Promise<DecisionSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DecisionSchema[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DecisionSchema[]>(null as any);
    }

    /**
     * List all Knowledge Base articles
     * @param type (optional) Filter by category type
     * @param tag (optional) Filter by tag
     * @return Successful Response
     */
    listArticles(type?: Anonymous | undefined, tag?: Tag | undefined): Promise<KBArticleSchema[]> {
        let url_ = this.baseUrl + "/api/kb?";
        if (type === null)
            throw new globalThis.Error("The parameter 'type' cannot be null.");
        else if (type !== undefined)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        if (tag === null)
            throw new globalThis.Error("The parameter 'tag' cannot be null.");
        else if (tag !== undefined)
            url_ += "tag=" + encodeURIComponent("" + tag) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListArticles(_response);
        });
    }

    protected processListArticles(response: Response): Promise<KBArticleSchema[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as KBArticleSchema[];
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<KBArticleSchema[]>(null as any);
    }

    /**
     * Search Knowledge Base and entities
     * @param q (optional) Search query string
     * @param tag (optional) Filter by tag
     * @param type (optional) Filter by entity type (kb, issue, decision, session)
     * @return Successful Response
     */
    searchKb(q?: string | undefined, tag?: Anonymous2 | undefined, type?: Anonymous3 | undefined): Promise<SearchResponse> {
        let url_ = this.baseUrl + "/api/kb/search?";
        if (q === null)
            throw new globalThis.Error("The parameter 'q' cannot be null.");
        else if (q !== undefined)
            url_ += "q=" + encodeURIComponent("" + q) + "&";
        if (tag === null)
            throw new globalThis.Error("The parameter 'tag' cannot be null.");
        else if (tag !== undefined)
            url_ += "tag=" + encodeURIComponent("" + tag) + "&";
        if (type === null)
            throw new globalThis.Error("The parameter 'type' cannot be null.");
        else if (type !== undefined)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSearchKb(_response);
        });
    }

    protected processSearchKb(response: Response): Promise<SearchResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SearchResponse;
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SearchResponse>(null as any);
    }

    /**
     * Get Knowledge Base cross-link graph
     * @return Successful Response
     */
    getKbGraph(): Promise<KBGraphSchema> {
        let url_ = this.baseUrl + "/api/kb/graph";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetKbGraph(_response);
        });
    }

    protected processGetKbGraph(response: Response): Promise<KBGraphSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as KBGraphSchema;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<KBGraphSchema>(null as any);
    }

    /**
     * Get single Knowledge Base article
     * @return Successful Response
     */
    getArticle(slug: string): Promise<KBArticleSchema> {
        let url_ = this.baseUrl + "/api/kb/{slug}";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetArticle(_response);
        });
    }

    protected processGetArticle(response: Response): Promise<KBArticleSchema> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as KBArticleSchema;
            return result200;
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            result422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HTTPValidationError;
            return throwException("Validation Error", status, _responseText, _headers, result422);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<KBArticleSchema>(null as any);
    }

    /**
     * Stream live repository changes via Server-Sent Events (SSE)
     * @return Successful Response
     */
    streamEvents(): Promise<any> {
        let url_ = this.baseUrl + "/api/events";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamEvents(_response);
        });
    }

    protected processStreamEvents(response: Response): Promise<any> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<any>(null as any);
    }
}

/** Aggregated project metrics. */
export interface DashboardMetricsSchema {
    total_issues: number;
    open_issues: number;
    in_progress_issues: number;
    blocked_issues: number;
    done_issues: number;
    completion_pct: number;
    active_risks: number;
    active_milestones: number;
    total_kb_articles: number;
    total_decisions: number;
    total_sessions: number;
    by_status: StatusBreakdown;
    by_type: TypeBreakdown;
    by_priority: PriorityBreakdown;
    scan_timestamp: string;

    [key: string]: any;
}

/** Schema for an ADR entry in .along/DECISIONS.md. */
export interface DecisionSchema {
    /** Decision identifier, e.g. ADR-001 */
    id: string;
    /** Sequential ADR number */
    number: Number;
    /** Decision title */
    title: string;
    /** Date recorded YYYY-MM-DD */
    date: Date;
    /** ADR status (Accepted, Superseded, etc.) */
    status: string;
    /** Context and problem description */
    context: Context;
    /** Decision made */
    decision: Decision;
    /** Consequences and trade-offs */
    consequences: Consequences;
    /** ADR identifier that supersedes this */
    superseded_by: Superseded_by;
    /** Full raw markdown of the entry */
    raw_markdown: Raw_markdown;

    [key: string]: any;
}

/** Complete dataset for dashboard SPA. */
export interface FullDashboardDataSchema {
    repo_name: string;
    metrics: DashboardMetricsSchema;
    issues: IssueSchema[];
    milestones: MilestoneSchema[];
    risks: RiskSchema[];
    spikes: SpikeSchema[];
    sessions: SessionSchema[];
    decisions: DecisionSchema[];
    kb_articles: KBArticleSchema[];
    graph: any;
    context_text: string;
    issues_board_text: string;

    [key: string]: any;
}

export interface HTTPValidationError {
    detail: ValidationError[];

    [key: string]: any;
}

/** Schema for .along/ISSUES/<type>--<slug>.md. */
export interface IssueSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: Title;
    /** Markdown body content */
    body: Body;
    /** Relative file path in repository */
    file_path: File_path;
    /** Issue type */
    type: IssueSchemaType;
    /** Current lifecycle status */
    status: IssueSchemaStatus;
    /** Priority level */
    priority: IssueSchemaPriority;
    /** Creation date YYYY-MM-DD */
    created: Created;
    /** Last update date YYYY-MM-DD */
    updated: Updated;
    /** Completion date YYYY-MM-DD */
    completed: Completed;
    /** Agent or author that worked on the issue */
    agent: Agent;
    /** Array of topical tags */
    tags: string[];
    /** Milestone slug this issue belongs to */
    milestone: Milestone2;
    /** List of blocking entity keys */
    blocked_by: string[];
    /** List of related entity keys */
    related: string[];
    /** Parent epic/entity key */
    parent: Parent;

    [key: string]: any;
}

/** Schema for Knowledge Base article in .along/KB/ or docs/. */
export interface KBArticleSchema {
    /** Unique article ID, e.g. kb--architecture or docs--setup */
    id: string;
    /** Article slug or filename */
    slug: string;
    /** Article title */
    title: string;
    /** Article topic category */
    type: KBArticleSchemaType;
    /** Creation date YYYY-MM-DD */
    created: Created2;
    /** Last update date YYYY-MM-DD */
    updated: Updated2;
    /** List of topic tags */
    tags: string[];
    /** Relative path in repository */
    file_path: string;
    /** Markdown body */
    body: string;
    /** Extracted Markdown headings */
    headings: string[];
    /** Outgoing wiki or entity links */
    outgoing_links: string[];
    /** Incoming links referencing this article */
    incoming_links: string[];

    [key: string]: any;
}

export interface KBGraphEdge {
    source: string;
    target: string;
    type: string;
    label: Label;

    [key: string]: any;
}

export interface KBGraphNode {
    id: string;
    label: string;
    type: string;
    category: string;
    tags: string[];

    [key: string]: any;
}

/** Bidirectional graph of Knowledge Base articles and related entities. */
export interface KBGraphSchema {
    nodes: KBGraphNode[];
    edges: KBGraphEdge[];

    [key: string]: any;
}

/** Schema for .along/MILESTONES/<slug>.md. */
export interface MilestoneSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: Title2;
    /** Markdown body content */
    body: Body2;
    /** Relative file path in repository */
    file_path: File_path2;
    /** Milestone status */
    status: MilestoneSchemaStatus;
    /** Target due date YYYY-MM-DD */
    due_date: Due_date;
    /** Creation date YYYY-MM-DD */
    created: Created3;
    /** Target issue slugs or keys */
    target_issues: string[];
    /** Completion percentage */
    progress_pct: number;

    [key: string]: any;
}

export interface PriorityBreakdown {
    critical: number;
    high: number;
    medium: number;
    low: number;

    [key: string]: any;
}

/** Schema for .along/RISKS/<slug>.md. */
export interface RiskSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: Title3;
    /** Markdown body content */
    body: Body3;
    /** Relative file path in repository */
    file_path: File_path3;
    /** Risk severity level */
    severity: RiskSchemaSeverity;
    /** Risk status */
    status: RiskSchemaStatus;
    /** Owner (agent or user) */
    owner: Owner;
    /** Mitigation strategy summary */
    mitigation: Mitigation;
    /** Creation date YYYY-MM-DD */
    created: Created4;
    /** Update date YYYY-MM-DD */
    updated: Updated3;

    [key: string]: any;
}

export interface SearchResponse {
    query: string;
    total: number;
    results: SearchResultItem[];

    [key: string]: any;
}

export interface SearchResultItem {
    id: string;
    title: string;
    type: string;
    snippet: string;
    file_path: string;
    score: number;
    tags: string[];

    [key: string]: any;
}

/** Schema for .along/SESSIONS/<YYYY>/<YYYY-MM-DD>--<slug>.md. */
export interface SessionSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: Title4;
    /** Markdown body content */
    body: Body4;
    /** Relative file path in repository */
    file_path: File_path4;
    /** Session date YYYY-MM-DD */
    date: string;
    /** Agent model/tool name */
    agent: Agent2;
    /** Git branch name */
    branch: Branch;
    /** Git commit hash */
    commit: Commit;
    /** Summary of work completed */
    summary: Summary;
    /** Associated milestone */
    milestone: Milestone3;
    /** Advanced issue keys */
    issues_advanced: string[];
    /** Completed issue keys */
    issues_completed: string[];
    /** Recorded ADR numbers/titles */
    decisions: string[];
    /** Logged risk keys */
    risks_logged: string[];
    /** Conducted spike keys */
    spikes_conducted: string[];

    [key: string]: any;
}

/** Schema for .along/SPIKES/<slug>.md. */
export interface SpikeSchema {
    /** Protocol identifier */
    protocol: string;
    /** Unique kebab-case slug of the entity */
    slug: string;
    /** Canonical entity identifier, e.g. feat--login */
    id: string;
    /** Human readable title */
    title: Title5;
    /** Markdown body content */
    body: Body5;
    /** Relative file path in repository */
    file_path: File_path5;
    /** Spike state */
    status: SpikeSchemaStatus;
    /** Spike hypothesis statement */
    hypothesis: Hypothesis;
    /** Spike outcome and conclusion */
    outcome: Outcome;
    /** Linked ADR in DECISIONS.md */
    resulting_adr: Resulting_adr;
    /** Creation date YYYY-MM-DD */
    created: Created5;

    [key: string]: any;
}

export interface StatusBreakdown {
    open: number;
    in_progress: number;
    blocked: number;
    done: number;

    [key: string]: any;
}

export interface TypeBreakdown {
    feat: number;
    bug: number;
    debt: number;
    task: number;
    docs: number;

    [key: string]: any;
}

export interface ValidationError {
    loc: Loc[];
    msg: string;
    type: string;
    input: any;
    ctx: any;

    [key: string]: any;
}

/** Filter by status (open, in-progress, blocked, done) */
export interface Status {

    [key: string]: any;
}

/** Filter by type (feat, bug, debt, task, docs) */
export interface Type {

    [key: string]: any;
}

/** Filter by priority (critical, high, medium, low) */
export interface Priority {

    [key: string]: any;
}

/** Filter by milestone slug */
export interface Milestone {

    [key: string]: any;
}

/** Filter by category type */
export interface Anonymous {

    [key: string]: any;
}

/** Filter by tag */
export interface Tag {

    [key: string]: any;
}

/** Filter by tag */
export interface Anonymous2 {

    [key: string]: any;
}

/** Filter by entity type (kb, issue, decision, session) */
export interface Anonymous3 {

    [key: string]: any;
}

export interface Number {

    [key: string]: any;
}

export interface Date {

    [key: string]: any;
}

export interface Context {

    [key: string]: any;
}

export interface Decision {

    [key: string]: any;
}

export interface Consequences {

    [key: string]: any;
}

export interface Superseded_by {

    [key: string]: any;
}

export interface Raw_markdown {

    [key: string]: any;
}

export interface Title {

    [key: string]: any;
}

export interface Body {

    [key: string]: any;
}

export interface File_path {

    [key: string]: any;
}

export enum IssueSchemaType {
    Feat = "feat",
    Bug = "bug",
    Debt = "debt",
    Task = "task",
    Docs = "docs",
}

export enum IssueSchemaStatus {
    Open = "open",
    InProgress = "in-progress",
    Blocked = "blocked",
    Done = "done",
}

export enum IssueSchemaPriority {
    Critical = "critical",
    High = "high",
    Medium = "medium",
    Low = "low",
}

export interface Created {

    [key: string]: any;
}

export interface Updated {

    [key: string]: any;
}

export interface Completed {

    [key: string]: any;
}

export interface Agent {

    [key: string]: any;
}

export interface Milestone2 {

    [key: string]: any;
}

export interface Parent {

    [key: string]: any;
}

export enum KBArticleSchemaType {
    Topic = "topic",
    Architecture = "architecture",
    DomainModel = "domain-model",
    SetupWorkflow = "setup-workflow",
    Index = "index",
    Doc = "doc",
}

export interface Created2 {

    [key: string]: any;
}

export interface Updated2 {

    [key: string]: any;
}

export interface Label {

    [key: string]: any;
}

export interface Title2 {

    [key: string]: any;
}

export interface Body2 {

    [key: string]: any;
}

export interface File_path2 {

    [key: string]: any;
}

export enum MilestoneSchemaStatus {
    Open = "open",
    InProgress = "in-progress",
    Completed = "completed",
}

export interface Due_date {

    [key: string]: any;
}

export interface Created3 {

    [key: string]: any;
}

export interface Title3 {

    [key: string]: any;
}

export interface Body3 {

    [key: string]: any;
}

export interface File_path3 {

    [key: string]: any;
}

export enum RiskSchemaSeverity {
    Critical = "critical",
    High = "high",
    Medium = "medium",
    Low = "low",
}

export enum RiskSchemaStatus {
    Active = "active",
    Mitigated = "mitigated",
    Resolved = "resolved",
}

export interface Owner {

    [key: string]: any;
}

export interface Mitigation {

    [key: string]: any;
}

export interface Created4 {

    [key: string]: any;
}

export interface Updated3 {

    [key: string]: any;
}

export interface Title4 {

    [key: string]: any;
}

export interface Body4 {

    [key: string]: any;
}

export interface File_path4 {

    [key: string]: any;
}

export interface Agent2 {

    [key: string]: any;
}

export interface Branch {

    [key: string]: any;
}

export interface Commit {

    [key: string]: any;
}

export interface Summary {

    [key: string]: any;
}

export interface Milestone3 {

    [key: string]: any;
}

export interface Title5 {

    [key: string]: any;
}

export interface Body5 {

    [key: string]: any;
}

export interface File_path5 {

    [key: string]: any;
}

export enum SpikeSchemaStatus {
    Hypothesis = "hypothesis",
    Evaluating = "evaluating",
    Concluded = "concluded",
}

export interface Hypothesis {

    [key: string]: any;
}

export interface Outcome {

    [key: string]: any;
}

export interface Resulting_adr {

    [key: string]: any;
}

export interface Created5 {

    [key: string]: any;
}

export interface Loc {

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}